# Generated by Django 6.0 on 2026-05-09 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_department_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(related_name='departments', through='guide.DepartmentEmployee', to=settings.AUTH_USER_MODEL),
        ),
    ]
