# Generated by Django 6.0.2 on 2026-02-04 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('template', models.TextField(blank=True, help_text='Шаблон отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_creators', models.ManyToManyField(blank=True, related_name='creatable_report_types', to=settings.AUTH_USER_MODEL, verbose_name='Кто может создавать')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='stakeholder_report_types', to=settings.AUTH_USER_MODEL, verbose_name='Заинтересованные лица')),
            ],
            options={
                'verbose_name': 'Тип отчета',
                'verbose_name_plural': 'Типы отчетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('clickhouse_table', models.CharField(blank=True, max_length=200, verbose_name='Таблица ClickHouse')),
                ('clickhouse_query', models.TextField(blank=True, verbose_name='Запрос ClickHouse')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные отчета')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reporttype', verbose_name='Тип отчета')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает утверждения'), ('approved', 'Утвержден'), ('rejected', 'Отклонен'), ('in_progress', 'В работе'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('priority', models.IntegerField(choices=[(1, 'Высокий'), (2, 'Средний'), (3, 'Низкий')], default=3, verbose_name='Приоритет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_requests', to='Reports.department', verbose_name='Подразделение')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='Reports.report', verbose_name='Созданный отчет')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='Reports.reporttype', verbose_name='Тип отчета')),
            ],
            options={
                'verbose_name': 'Запрос отчета',
                'verbose_name_plural': 'Запросы отчетов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='Reports_rep_status_37670f_idx'), models.Index(fields=['requester', 'status'], name='Reports_rep_request_e1f1d0_idx'), models.Index(fields=['department', 'status'], name='Reports_rep_departm_215a21_idx'), models.Index(fields=['created_at'], name='Reports_rep_created_6954b4_idx')],
            },
        ),
    ]
