# Generated by Django 6.0.2 on 2026-02-06 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('rank', models.CharField(blank=True, max_length=100, verbose_name='Звание')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('additional_data', models.TextField(blank=True, help_text='Дополнительная информация', verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='Reports.department', verbose_name='Отдел')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персональные данные',
                'verbose_name_plural': 'Персональные данные',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='Reports_per_last_na_ef48ef_idx'), models.Index(fields=['is_active'], name='Reports_per_is_acti_393413_idx'), models.Index(fields=['department', 'is_active'], name='Reports_per_departm_efebab_idx'), models.Index(fields=['hire_date'], name='Reports_per_hire_da_638727_idx'), models.Index(fields=['position'], name='Reports_per_positio_9e26d5_idx')],
            },
        ),
    ]
