# Generated by Django 6.0 on 2026-02-06 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_delete_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='report',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил'),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
