# Generated by Django 6.0 on 2026-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('zl', 'ZL'), ('user', 'Пользователь')], db_index=True, default='user', help_text='Роль пользователя определяет доступ к различным разделам системы', max_length=10),
        ),
    ]
