# Generated by Django 6.0 on 2026-02-06 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход'), ('logout', 'Выход'), ('approve', 'Утверждение'), ('reject', 'Отклонение'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Тип действия')),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Тип ресурса')),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID ресурса')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись лога аудита',
                'verbose_name_plural': 'Лог аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_user_ts_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_action_ts_idx'), models.Index(fields=['timestamp'], name='audit_timestamp_idx')],
            },
        ),
    ]
