# Generated by Django 6.0 on 2026-05-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kripton', '0002_realtime_event_user_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='realtimeevent',
            new_name='kripton_rea_user_id_122d0d_idx',
            old_name='kripton_rea_user_id_5b0b0d_idx',
        ),
    ]
